name: Test

on:
  push:
    branches:
      - master
      - main

  pull_request:
  # manual trigger
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
      
      - name: Copy env file
        run: cp .env.example .env

      - name: Testing
        run: npm test